### ISSUE TITLE
Unable to import GPX Track to Garmin Basecamp

### ISSUE THREAD

**Issue by johnjore** [MichaelFCoyle/SharpGPX#2]
Hi!
Thanks for creating this! I had to make 3x changes to a track for it to import to Garmin Basecamp:

1) Add version = "1.1" to the header:
`<gpx version = "1.1" xmlns:xsd="`

2) remove empty email tag
      <email />

3) remove empty license tag
      <license />

**Comment by MichaelFCoyle** [comment]
Hi John, 

Thanks for reporting this. 

Regarding the version attribute:
I don't think it is part of the GPX standard - from my reading it uses the namespace  xmlns="http://www.topografix.com/GPX/1/1" to indicate the version.

I'll look into what issues it might cause to add this attribute, I could make it optional but then I'll need to set an options structure to handle these exceptions. This was always a possibility.

Regarding the email and license tags, I'm surmising you're saying two things
1) SharpGPS is generating blank tags for both those things and
2) Mapsource is choking on it.

The XML is still valid and while it doesn't help to say it, this means MapSource isn't following the standard.

I'll modify SharpGPX to not emit blank tags and make it standard behaviour.

**Comment by johnjore** [comment]
Hi and yes, you're comments are spot on. And thanks!

**Comment by MichaelFCoyle** [comment]
Hi John, I do not have a version of Garmin Basecamp to test with. Please let me know if this addresses the issue and and thanks again for reporting.

I looked into the Version attribute in particular and that is actually required by the spec, and I missed it. This is important so I can continue to claim this library produces correct and valid XML!

**Comment by johnjore** [comment]
Hi and yes, the latest nuget package, 2.21.524, has fixed the issue with Garmin Basecamp.
Thanks for the quick turnaround!
