### ISSUE TITLE
Allow for using custom XmlSerializer settings

### ISSUE THREAD

**Issue by blainne** [MichaelFCoyle/SharpGPX#5]
Hi, would it be possible to allow to use custom serialization settings from public API?

I'm experimenting with uploading files processed by SharpGPX to Strava and it seems that they don't accept UTF-16 encoded files.
I'd like to be able to configure the serialization so that it's possible to create and UTF-8 file.

I spent quite some time analyzing the source code and I think I have some ideas, so I could prepare a PR if You want some help, but I think it would be good to read some comment from You side before that.

**Comment by MichaelFCoyle** [comment]
This is an excellent idea!

I exposed XmlWriterSettings as a static property on the GpxClass so you can set it once.

I discovered a bug where the encoding wasn't honoured by the StringWriter in ToXml(); Applying both in a few minutes, and I'll update the Nuget package as well.

**Comment by blainne** [comment]
Works like a charm now, thank You :)
